services:
  server:
    build:
      context: ./api
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    networks:
      - planner_network
    ports:
      - "3000:3000"

  client:
    build:
      context: ./client
    depends_on:
      - server
    networks:
      - planner_network
    ports:
      - "4173:4173"

networks:
  planner_network:
    driver: bridge
    