services:
  server:
    build: ./api
    environment:
      - HOST=0.0.0.0
    networks:
      - planner_network
    ports:
      - "3000:3000"

  client:
    build: ./client
    environment:
      - VITE_SERVER_URL=http://localhost/api
    depends_on:
      - server
    networks:
      - planner_network
    ports:
      - "4173:4173"

networks:
  planner_network:
    driver: bridge
    